parameters:
#    disycs_blog.example.class: Disycs\BlogBundle\Example

services:
#    disycs_blog.example:
#        class: %disycs_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
